### ISSUE TITLE
Support building without sourcemaps

### ISSUE THREAD

**Issue by hipstersmoothie** [isaacs/tshy#56]
Had to turn on source maps in my tsconfig to get past this error

```
Error: ENOENT: no such file or directory, unlink '/Users/andrewlisowski/Documents/jimp/plugins/plugin-print/.tshy-build/browser/load-font.js.map'
    at unlinkSync (node:fs:1881:3)
    at buildESM (file:///Users/andrewlisowski/Documents/jimp/node_modules/.pnpm/tshy@1.12.0/node_modules/tshy/dist/esm/build-esm.js:29:13)
    at default (file:///Users/andrewlisowski/Documents/jimp/node_modules/.pnpm/tshy@1.12.0/node_modules/tshy/dist/esm/build.js:19:9)
    at async main (file:///Users/andrewlisowski/Documents/jimp/node_modules/.pnpm/tshy@1.12.0/node_modules/tshy/dist/esm/index.js:26:5)
    at async file:///Users/andrewlisowski/Documents/jimp/node_modules/.pnpm/tshy@1.12.0/node_modules/tshy/dist/esm/index.js:29:1 {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Users/andrewlisowski/Documents/jimp/plugins/plugin-print/.tshy-build/browser/load-font.js.map'
}
```

**Comment by hipstersmoothie** [comment]
@isaacs Thanks!
